using System.Windows;
using System.Windows.Media;
using Microsoft.Toolkit.Mvvm.ComponentModel;

namespace LibDisplayPlc.ViewModel;

public partial class VmPlc
{
    [ObservableProperty] private Brush _brushDa00;
    [ObservableProperty] private Brush _brushDa01;
    [ObservableProperty] private Brush _brushDa02;
    [ObservableProperty] private Brush _brushDa03;
    [ObservableProperty] private Brush _brushDa04;
    [ObservableProperty] private Brush _brushDa05;
    [ObservableProperty] private Brush _brushDa06;
    [ObservableProperty] private Brush _brushDa07;
    [ObservableProperty] private Brush _brushDa10;
    [ObservableProperty] private Brush _brushDa11;
    [ObservableProperty] private Brush _brushDa12;
    [ObservableProperty] private Brush _brushDa13;
    [ObservableProperty] private Brush _brushDa14;
    [ObservableProperty] private Brush _brushDa15;
    [ObservableProperty] private Brush _brushDa16;
    [ObservableProperty] private Brush _brushDa17;
    [ObservableProperty] private Brush _brushDa20;
    [ObservableProperty] private Brush _brushDa21;
    [ObservableProperty] private Brush _brushDa22;
    [ObservableProperty] private Brush _brushDa23;
    [ObservableProperty] private Brush _brushDa24;
    [ObservableProperty] private Brush _brushDa25;
    [ObservableProperty] private Brush _brushDa26;
    [ObservableProperty] private Brush _brushDa27;

    [ObservableProperty] private Visibility _visibilityDa00;
    [ObservableProperty] private Visibility _visibilityDa01;
    [ObservableProperty] private Visibility _visibilityDa02;
    [ObservableProperty] private Visibility _visibilityDa03;
    [ObservableProperty] private Visibility _visibilityDa04;
    [ObservableProperty] private Visibility _visibilityDa05;
    [ObservableProperty] private Visibility _visibilityDa06;
    [ObservableProperty] private Visibility _visibilityDa07;
    [ObservableProperty] private Visibility _visibilityDa10;
    [ObservableProperty] private Visibility _visibilityDa11;
    [ObservableProperty] private Visibility _visibilityDa12;
    [ObservableProperty] private Visibility _visibilityDa13;
    [ObservableProperty] private Visibility _visibilityDa14;
    [ObservableProperty] private Visibility _visibilityDa15;
    [ObservableProperty] private Visibility _visibilityDa16;
    [ObservableProperty] private Visibility _visibilityDa17;
    [ObservableProperty] private Visibility _visibilityDa20;
    [ObservableProperty] private Visibility _visibilityDa21;
    [ObservableProperty] private Visibility _visibilityDa22;
    [ObservableProperty] private Visibility _visibilityDa23;
    [ObservableProperty] private Visibility _visibilityDa24;
    [ObservableProperty] private Visibility _visibilityDa25;
    [ObservableProperty] private Visibility _visibilityDa26;
    [ObservableProperty] private Visibility _visibilityDa27;

    [ObservableProperty] private string _stringBezeichnungDa00;
    [ObservableProperty] private string _stringBezeichnungDa01;
    [ObservableProperty] private string _stringBezeichnungDa02;
    [ObservableProperty] private string _stringBezeichnungDa03;
    [ObservableProperty] private string _stringBezeichnungDa04;
    [ObservableProperty] private string _stringBezeichnungDa05;
    [ObservableProperty] private string _stringBezeichnungDa06;
    [ObservableProperty] private string _stringBezeichnungDa07;
    [ObservableProperty] private string _stringBezeichnungDa10;
    [ObservableProperty] private string _stringBezeichnungDa11;
    [ObservableProperty] private string _stringBezeichnungDa12;
    [ObservableProperty] private string _stringBezeichnungDa13;
    [ObservableProperty] private string _stringBezeichnungDa14;
    [ObservableProperty] private string _stringBezeichnungDa15;
    [ObservableProperty] private string _stringBezeichnungDa16;
    [ObservableProperty] private string _stringBezeichnungDa17;
    [ObservableProperty] private string _stringBezeichnungDa20;
    [ObservableProperty] private string _stringBezeichnungDa21;
    [ObservableProperty] private string _stringBezeichnungDa22;
    [ObservableProperty] private string _stringBezeichnungDa23;
    [ObservableProperty] private string _stringBezeichnungDa24;
    [ObservableProperty] private string _stringBezeichnungDa25;
    [ObservableProperty] private string _stringBezeichnungDa26;
    [ObservableProperty] private string _stringBezeichnungDa27;

    [ObservableProperty] private string _stringKommentarDa00;
    [ObservableProperty] private string _stringKommentarDa01;
    [ObservableProperty] private string _stringKommentarDa02;
    [ObservableProperty] private string _stringKommentarDa03;
    [ObservableProperty] private string _stringKommentarDa04;
    [ObservableProperty] private string _stringKommentarDa05;
    [ObservableProperty] private string _stringKommentarDa06;
    [ObservableProperty] private string _stringKommentarDa07;
    [ObservableProperty] private string _stringKommentarDa10;
    [ObservableProperty] private string _stringKommentarDa11;
    [ObservableProperty] private string _stringKommentarDa12;
    [ObservableProperty] private string _stringKommentarDa13;
    [ObservableProperty] private string _stringKommentarDa14;
    [ObservableProperty] private string _stringKommentarDa15;
    [ObservableProperty] private string _stringKommentarDa16;
    [ObservableProperty] private string _stringKommentarDa17;
    [ObservableProperty] private string _stringKommentarDa20;
    [ObservableProperty] private string _stringKommentarDa21;
    [ObservableProperty] private string _stringKommentarDa22;
    [ObservableProperty] private string _stringKommentarDa23;
    [ObservableProperty] private string _stringKommentarDa24;
    [ObservableProperty] private string _stringKommentarDa25;
    [ObservableProperty] private string _stringKommentarDa26;
    [ObservableProperty] private string _stringKommentarDa27;

    [ObservableProperty] private string _stringWertDa0;
    [ObservableProperty] private string _stringWertDa1; 
    [ObservableProperty] private string _stringWertDa2;
}